### ISSUE TITLE
Interactive mailing pigeon hidden in scences 

### ISSUE THREAD

**Issue by Dobios** [GameLab-UNIL-EPFL/Lausanne-1830#100]
The idea is to have one of the pigeons not fly away on approach. 
This pigeon can then be interacted with to fetch information that's out of reach.

In order to unlock this pigeon, we need to make sure that the pigeon flies to a specific rooftop and recovers a visible piece of paper.  
Once the paper is retrieved by the pigeon, we can interact with it to read the information.

**Comment by yrochat** [comment]
I love that!

Le mar. 22 mars 2022 à 11:35, Andrew Dobis ***@***.***> a
écrit :
