### ISSUE TITLE
Beer brewing minigame

### ISSUE THREAD

**Issue by Dobios** [GameLab-UNIL-EPFL/Lausanne-1830#103]
The idea is to have a minigame related to brewing beer. This would be similar to the cooking minigame in the GBA pokemon games.    
The minigame would be initiated by talking to Trüschel in the brewery, where she would mention not having time to answer the player's questions. Then if the player talks to one of the brewers, they will be thrown into the brewing minigame.  
  
The concept is to press the arrow keys at the right time to stir the beer, too slow and it burns, too fast and it overflows.

**Comment by yrochat** [comment]
I love that too! I'm ready to talk to the teachers if this stirs any
controversy.

Le mar. 22 mars 2022 à 11:49, Andrew Dobis ***@***.***> a
écrit :
