### ISSUE TITLE
Fishing mini-game

### ISSUE THREAD

**Issue by Dobios** [GameLab-UNIL-EPFL/Lausanne-1830#108]
Have a fisherman prompt the player to start fishing.  
Then cut to a new scene where we have the player standing above the river and implement fishing animal-crossing style (a fish shadow approaching the bait and the player needs to press `E` right when the fish reaches the bait).

**Comment by yrochat** [comment]
👀

Le mar. 22 mars 2022 à 13:14, Andrew Dobis ***@***.***> a
écrit :
