### ISSUE TITLE
Character Romance Option

### ISSUE THREAD

**Issue by pandreu** [GameLab-UNIL-EPFL/Lausanne-1830#124]
Some of the characters keep talking about strangers to love, and how'd they never get this from any other guy. Is this hinting at the addition of romance quests in later builds of the game?

**Comment by Dobios** [comment]
Unfortunately we are going to have to scrap this idea due to time constraints sorry ^^"

**Comment by yrochat** [comment]
😢

Le mar. 14 juin 2022 à 20:57, Andrew Dobis ***@***.***> a
écrit :
