### ISSUE TITLE
Moulin art 

### ISSUE THREAD

**Issue by sarsurgithub** [GameLab-UNIL-EPFL/Lausanne-1830#143]
- [x] bat1
- [x] bat2
- [x] bat3
- [x] arbres
- [x] pont1
- [ ] pont2
- [x] herbes
- [x] flon
- [x] 9 enfants
- [x] 3 persos
- [x] buissons 
- [x] chemin
- [ ] cailloux

**Comment by astonedf** [comment]
- [] random vignerons & paysans npcs
