### ISSUE TITLE
The wrong portrait is displayed on Rochat's page

### ISSUE THREAD

**Issue by astonedf** [GameLab-UNIL-EPFL/Lausanne-1830#159]
Need to save the right portrait in Context, so when we change scenes it displays the right portrait and not Portrait0

**Comment by Gallouche** [comment]
I want to add more context here, while trying the game yesterday, I noticed the same but on M. Perregaux's portrait. Replayed the game today and had the same issue with M.Mercier. I did the tasks in another order than yesterday, could be related.
<img width="411" alt="Screenshot 2022-05-16 at 08 22 02" src="https://user-images.githubusercontent.com/25899971/168532023-9cb59c8f-8a05-4903-9454-c95c0b913e00.png">
But then when I finished the tasks, M.Mercier's portrait turned empty 🤔 
<img width="411" alt="Screenshot 2022-05-16 at 08 23 34" src="https://user-images.githubusercontent.com/25899971/168532131-99cecf8c-616b-4308-957b-bf2960d5e4ce.png">
And as you can see M. Rochat's page is fine for me.
<img width="411" alt="Screenshot 2022-05-16 at 08 22 20" src="https://user-images.githubusercontent.com/25899971/168532193-efc44598-d9c4-452e-b77d-48a4d70f291e.png">

**Comment by Dobios** [comment]
Yeah we currently don't store the portrait in the game's context (persistent state object), and since the Notebook is reloaded for each scene, the portrait retakes the default state (portrait0). Will fix __ASAP__.
