### ISSUE TITLE
Some bug found 🐛 

### ISSUE THREAD

**Issue by Gallouche** [GameLab-UNIL-EPFL/Lausanne-1830#160]
Hello! First of all very nice work and congrats to the whole team 🎉 (specifically to @sarsurgithub ❤️  lol). While playing it I found some little bugs (or not), so I'm sharing them.
- When you speak to a character that is close to the edge of the screen, the dialogue box is truncated and you can only read it partially.
- There is pigeon staying first layer when you open the butcher "panel"
![photo_2022-05-16_08-34-01](https://user-images.githubusercontent.com/25899971/168532923-67acdc8b-b53f-452b-b189-c968acded936.jpg)
- Not sure if it's a bug or a feature but only F1 to F4 works when there are 6 tabs, and F1 open the 2nd one, and all are like shifted.
- I have no ending after completing the tasks and getting back to M.Gély... It says "je vous ouvre la porte..." but nothing happend.
<img width="584" alt="Screenshot 2022-05-16 at 08 24 06" src="https://user-images.githubusercontent.com/25899971/168533246-aefb1bc0-1ea7-4a5b-a6cd-6dc7bad9904c.png">
Then nothing:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/25899971/168533336-c6cf0f66-2a85-4098-b60d-f7316a38aeda.png">
Ping me if you need more context :)

**Comment by Dobios** [comment]
> Hello! First of all very nice work and congrats to the whole team 🎉 (specifically to @sarsurgithub ❤️ lol). While playing it I found some little bugs (or not), so I'm sharing them.
>   
>     * When you speak to a character that is close to the edge of the screen, the dialogue box is truncated and you can only read it partially.  
This is a known bug, and is in the backburner to be fixed along with other NPC movement related bugs.  
> 
>     * There is pigeon staying first layer when you open the butcher "panel"
>       ![photo_2022-05-16_08-34-01](https://user-images.githubusercontent.com/25899971/168532923-67acdc8b-b53f-452b-b189-c968acded936.jpg)  
Lol forgot about that one, will fix __ASAP__.  
> 
>     * Not sure if it's a bug or a feature but only F1 to F4 works when there are 6 tabs, and F1 open the 2nd one, and all are like shifted.  
Definitely a bug, we recently added two new tabs but didn't update the input map (input jank comes with the `alpha` versioning ^^").   
> 
>     * I have no ending after completing the tasks and getting back to M.Gély... It says "je vous ouvre la porte..." but nothing happened.  
This is also a relic that hasn't been updated since we added the admin room. You actually do unlock the ending but it can only be accessed from the `Palud` scene, where the town hall has a newly opened door, but will also fix __ASAP__.  
> 
> 
> <img alt="Screenshot 2022-05-16 at 08 24 06" width="584" src="https://user-images.githubusercontent.com/25899971/168533246-aefb1bc0-1ea7-4a5b-a6cd-6dc7bad9904c.png">
> Then nothing:
> 
> <img alt="image" width="584" src="https://user-images.githubusercontent.com/25899971/168533336-c6cf0f66-2a85-4098-b60d-f7316a38aeda.png">
> Ping me if you need more context :)  
Thanks for the feedback! The mentioned bugs will be tackled as soon as possible!
