### ISSUE TITLE
Improvements suggestions

### ISSUE THREAD

**Issue by Gallouche** [GameLab-UNIL-EPFL/Lausanne-1830#161]
I'm suggesting some improvements, won't be sad if it's not in the pipeline :) 
- Played the game in French and in the number input modal, labels are still in English
- Could it be possible to put "esc" key as a default to quit every view/dialogue box? Could be more user friendly!
- I would recommend enabling the "tab" key at any moment (while on the map, while in a dialogue) so players can quickly add pieces of information they collect.
- About Mme Perregaux the dialogue says that she is waiting for her 3rd child, this misled me a bit because I put 3 children in M.Perregaux's tab as I had this vision of my present time, meaning the child is born and so they got 3. Dunno if what I say makes sense!

**Comment by Dobios** [comment]
These features were added in a recent PR.
