### ISSUE TITLE
Add solution NPC, that gives you your task and evaluates your solutions

### ISSUE THREAD

**Issue by Dobios** [GameLab-UNIL-EPFL/Lausanne-1830#18]

**Comment by astonedf** [comment]
Update the choices in the notebook instead of the quest NPC -> https://github.com/GameLab-UNIL-EPFL/Lausanne-1830/issues/21#issue-1081932491

**Comment by astonedf** [comment]
Add distinction between unfilled fields vs mistakes in the notebook (Champs faux vs champs non remplis) in the solution NPC's evaluation
