### ISSUE TITLE
Job Selection

### ISSUE THREAD

**Issue by laitkaci** [GameLab-UNIL-EPFL/Lausanne-1830#192]
Dans la sélection des métiers, "Ecrivain.e" ne respecte pas l'ordre alphabétique comme les autres métiers

**Comment by Dobios** [comment]
C'est "Écrivain" commençant par un charactère spéciale "É" et dans l'ordre alphabétique de WebGL les charactères spéciaux vont à la fin, donc l'ordre est repsecté.
