### ISSUE TITLE
Carnet UI

### ISSUE THREAD

**Issue by astonedf** [GameLab-UNIL-EPFL/Lausanne-1830#4]
![notebookExample](https://user-images.githubusercontent.com/58696128/144421009-b900ef67-2c92-4449-8d64-8d36a5831266.png)

-> updated notebook's draft

**Comment by Dobios** [comment]
## Implementation  

- [ ] Select field option  
- [ ] Select numeric option  
- [ ] Show Scene Objective  
- [ ] Only allow modification of wrong/incomplete fields
