### ISSUE TITLE
If an NPC is too close to an interactive item, the interaction won't appear

### ISSUE THREAD

**Issue by astonedf** [GameLab-UNIL-EPFL/Lausanne-1830#90]
Especially the bookshelf in the brewery

**Comment by astonedf** [comment]
Improved in the brewery
TODO: check in Palud and Casino

**Comment by Dobios** [comment]
Not really a bug, it's more of a feature since we decided, by design, that NPCs have precedence on items for interactions.

**Comment by astonedf** [comment]
Sure, but when the player has to walk 10 times in front of the table before the interaction prompt appears and realising there was an clue there it’s a design issue ^^’
